### PR TITLE
Ubuntu 16.04 compatibility fix

### PR DESCRIPTION
**Pull request by CalvinHartwell**
Hi all,

I had some trouble using this out of the box the other day on a fresh 16.04 customer install and for such a simple script this should be much easier to use. Two changes: 

- Use Python from the Path instead of enforcing the use of python3 as it is still widely used on 16.04 and there is nothing stopping it from working with python2 out of the box. 

- Added readme instructions for installing missing libraries and binaries to run the script. 

Cheers

### CODE REVIEW

**Comment by ktsakalozos** [comment]
Hi @CalvinHartwell . Thank you for the PR can you please rebase?

**Comment by Cynerva** [comment]
I have concerns:

1. Ubuntu 18.04 comes with `python3` installed, not `python`. So this "fixes" an older release but "breaks" the newer one.
2. You're adding instructions to install python 2 and several packages anyway, so what's the point of reverting? Why not instruct them to install python3 and python3 libs?

**Comment by ktsakalozos** [comment]
Something else you should be aware @CalvinHartwell is that this project was not meant to provide the released bundles. For example, from now and the next week the master head of this project will produce bundles for 1.11 kubernetes but the officially released cdk is with 1.10.

If you intent to use this project in the field we should create branches in a timely fashion.

**Comment by CalvinHartwell** [comment]
> Ubuntu 18.04 comes with python3 installed, not python. So this "fixes" an older release but "breaks" the newer one.
> 
> You're adding instructions to install python 2 and several packages anyway, so what's the point of reverting? Why not instruct them to install python3 and python3 libs?

Python3 is installed by default on 16.04, but just like RHEL6/7, it is not the default python release used by the OS. Usually this is because some OS utilities and binaries require the use of Python2. 

> Something else you should be aware @CalvinHartwell is that this project was not meant to provide the released bundles. For example, from now and the next week the master head of this project will produce bundles for 1.11 kubernetes but the officially released cdk is with 1.10.
> 
> If you intent to use this project in the field we should create branches in a timely fashion.

What do mean by this? Are you basically saying that the master branch should no longer be used for customer deployments and 1.11 is not supported yet? Do you want to us to deploy $currentversion-1 in the field instead of the most recent version? Please explain.

**Comment by ktsakalozos** [comment]
> What do mean by this? Are you basically saying that the master branch should no longer be used for customer deployments and 1.11 is not supported yet? Do you want to us to deploy $currentversion-1 in the field instead of the most recent version? Please explain.

This project is used to produce bundles that will go through our CI process and if they pass all testing they get released to the charm store. Our release ends with placing charms & bundles on the charm store we do _not_ release by patching this repository to build the latest bundles. This project was always an internal tool used in the late stages of our release process.

*My* opinion on what the field should do is to get the bundles from the store directly since this is where charms & bundles are released. Then write any pre and post-deploy scripts as [spells](https://github.com/conjure-up/spells/tree/master/canonical-kubernetes). I know that conjure-up does not fit your needs so just call your scripts directly. Yet, if you code your deployments in a structured way (eg spells) we could have a common ground where field and engineers could collaborate. Ultimately we would want to get your pre/post deploy scripts regularly tested through our CI.

Let me understand something, you are using this project to produce the bundles you juju deploy. If conjure-up was working in headless mode (no user interface) and would just output the bundle.yaml (no deployment no post/pre deploy steps) would the field consider it as an alternative to this project?

**Comment by johnsca** [comment]
Since this hasn't been updated or asked for in over 2 years, I think Konstantinos's comment that this is intended for internal use by our CI / build system stands, and so I'm closing this.  Feel free to re-open if there's still some need to use this outside of the CI / build system that I'm not aware of.

**Pull request closed without merging**
